// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_rolling_cor
NumericVector fast_rolling_cor(NumericVector x, NumericVector y, int window_size);
RcppExport SEXP _dormancy_fast_rolling_cor(SEXP xSEXP, SEXP ySEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rolling_cor(x, y, window_size));
    return rcpp_result_gen;
END_RCPP
}
// fast_conditional_cor
double fast_conditional_cor(NumericVector x, NumericVector y, NumericVector z, double z_min, double z_max);
RcppExport SEXP _dormancy_fast_conditional_cor(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP z_minSEXP, SEXP z_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type z_min(z_minSEXP);
    Rcpp::traits::input_parameter< double >::type z_max(z_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_conditional_cor(x, y, z, z_min, z_max));
    return rcpp_result_gen;
END_RCPP
}
// fast_entropy_2d
double fast_entropy_2d(NumericVector x, NumericVector y, int n_bins);
RcppExport SEXP _dormancy_fast_entropy_2d(SEXP xSEXP, SEXP ySEXP, SEXP n_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_entropy_2d(x, y, n_bins));
    return rcpp_result_gen;
END_RCPP
}
// fast_mutual_info
double fast_mutual_info(NumericVector x, NumericVector y, int n_bins);
RcppExport SEXP _dormancy_fast_mutual_info(SEXP xSEXP, SEXP ySEXP, SEXP n_binsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_bins(n_binsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_mutual_info(x, y, n_bins));
    return rcpp_result_gen;
END_RCPP
}
// fast_threshold_detect
List fast_threshold_detect(NumericVector x, NumericVector y, int n_thresholds);
RcppExport SEXP _dormancy_fast_threshold_detect(SEXP xSEXP, SEXP ySEXP, SEXP n_thresholdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_thresholds(n_thresholdsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_threshold_detect(x, y, n_thresholds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dormancy_fast_rolling_cor", (DL_FUNC) &_dormancy_fast_rolling_cor, 3},
    {"_dormancy_fast_conditional_cor", (DL_FUNC) &_dormancy_fast_conditional_cor, 5},
    {"_dormancy_fast_entropy_2d", (DL_FUNC) &_dormancy_fast_entropy_2d, 3},
    {"_dormancy_fast_mutual_info", (DL_FUNC) &_dormancy_fast_mutual_info, 3},
    {"_dormancy_fast_threshold_detect", (DL_FUNC) &_dormancy_fast_threshold_detect, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dormancy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
